version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-portfolio-react:latest
    container_name: portfolio_web
    ports:
      - "3000:80"
    restart: unless-stopped
